### ISSUE TITLE
Laser tactical device

### ISSUE THREAD

**Issue by emilanderss0n** [S3RAPH-1M/EscapeFromTarkov-SDK#21]
It would be amazing if we could have support for laser sights added.

**Comment by S3RAPH-1M** [comment]
Yeah give me some time & Ill add it. 👍

**Comment by S3RAPH-1M** [comment]
https://github.com/S3RAPH-1M/EscapeFromTarkov-SDK/pull/22

GrooveyPenguin got around to it. Closing the issue 👍
